import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignUp, SignedIn, SignedOut } from '@clerk/nextjs'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-slate-50 via-white to-slate-50 text-slate-800`}
        >
            <SignedOut>
          <section className="h-screen w-screen flex items-center justify-center p-6">
              <div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white/70 backdrop-blur-xl shadow-xl p-6">
                <SignUp />
              </div>
          </section>
            </SignedOut>
          <SignedIn>
            {children}
          </SignedIn>
        </body>
      </ClerkProvider>
    </html>
  );
}
